<?php

namespace App\Models;

use App\Traits\FilterByTenant;
use App\Traits\filterByUser;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory , filterByUser ;
    protected  $guarded = [];

    /******************  relations *************************/

    public function project(){
        return $this->belongsTo(Project::class);
    }

    /******************** functions ***************************/

    /*
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model){
            $model->user_id = auth()->id();
        });

        self::addGlobalScope(function (Builder $builder){
            $builder->where('user_id' , auth()->id());
        });
    }
    */
}
